### ISSUE TITLE
:Mark does not respect \V for some patterns?

### ISSUE THREAD

**Issue by justinmk** [inkarkat/vim-ingo-library#3]
**Describe the bug**

The following command yields error `E944: Reverse range in character class`:

    :Mark /\V[[a-S]]/

In contrast, using builtin `/` to search for `\V[[a-S]]` does not yield this error (but without `\V` it does).

**How to Reproduce**

Run the above command.

**Expected Behavior**

The `\V` should be respected and there should be no complaint about a character class because the `[...]`  should be treated as literal instead of magic.

**Environment**
 - Plugin version  https://github.com/inkarkat/vim-mark/commit/0afec1d5bb2547a9357eecca54fbc5c6c6d178a7
 - Dependency versions ingo-library  https://github.com/inkarkat/vim-ingo-library/commit/48ffe514bac9ddd5c7ece029a47a94f9dd31b935
 - Nvim 0.11 
 - OS: macos
 - Install method: git clone

**Comment by inkarkat** [comment]
Thanks for reporting this! I rarely change the magicness of patterns, so the normalization (which is handled by the ingo-library, not the Mark plugin) missed a corner case.
